version: '3'

services:
  email-relay-nginx:
    container_name: email-relay-nginx
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      # use the nginx.conf from this repo
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets/:/usr/share/nginx/assets:ro
    ports:
      - '8080:80'

  email-relay:
    container_name: email-relay
    image: ghcr.io/henrygd/email-relay-server:arm64
    restart: unless-stopped
    volumes:
      - ./assets:/assets
    environment:
      SMTP_HOST:
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SECRET_KEY_BASE:
